spring:
  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: http://localhost:8081
          predicates:
            - Path=/usuarios/**
        - id: categorias-service
          uri: http://localhost:8082
          predicates:
            - Path=/categorias/**
        - id: memes-service
          uri: http://localhost:8083
          predicates:
            - Path=/memes/**
        - id: meme-do-dia-service
          uri: http://localhost:8084
          predicates:
            - Path=/meme-do-dia/**
